.TH "fe" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fe \- Collection of methods and data related to mesh and fem\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBaseElem\fP"
.br
.RI "\fIA base class to compute and store quadrature data\&. \fP"
.ti -1c
.RI "class \fBMassMatrix\fP"
.br
.RI "\fIA class for mass matrix\&. \fP"
.ti -1c
.RI "class \fBMesh\fP"
.br
.RI "\fIA class for mesh data\&. \fP"
.ti -1c
.RI "struct \fBQuadData\fP"
.br
.RI "\fIA struct to store the quadrature data\&. \fP"
.ti -1c
.RI "class \fBQuadElem\fP"
.br
.RI "\fIA class for quadrature related operations for bi-linear quadrangle element\&. \fP"
.ti -1c
.RI "class \fBQuadrature\fP"
.br
.RI "\fIA class for quadrature related operations\&. \fP"
.ti -1c
.RI "class \fBTriElem\fP"
.br
.RI "\fIA class for quadrature related operations for linear triangle element\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of methods and data related to mesh and fem\&. 

This namespace provides methods and data members specific to mesh and finite element\&.
.PP
\fBSee also:\fP
.RS 4
\fBMesh\fP, \fBMassMatrix\fP, \fBQuadrature\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
