fe::BaseElem
NAME
fe::BaseElem - A base class to compute and store quadrature data.
SYNOPSIS
#include <baseElem.h>
Inherited by fe::QuadElem, and fe::TriElem.
Public Member Functions
BaseElem (size_t order, size_t element_type)
Constructor.
size_t getElemType ()
Get element type.
size_t getQuadOrder ()
Get order of quadrature approximation.
size_t getNumQuadPoints ()
Get number of quadrature points in the data.
virtual std::vector< fe::QuadData > getQuadPoints (const std::vector< util::Point3 > &nodes)=0
Get vector of quadrature data.
virtual std::vector< double > getShapes (const util::Point3 &p)=0
Returns the values of shape function at point p.
virtual std::vector< std::vector< double > > getDerShapes (const util::Point3 &p)=0
Returns the values of derivative of shape function.
virtual double mapRefElemToElem (util::Point3 &p, const std::vector< double > &shapes, const std::vector< std::vector< double >> &der_shapes, const std::vector< util::Point3 > &nodes)=0
Maps the point on reference element to given element and returns the determinant of Jacobian.
Private Member Functions
virtual void init ()=0
Compute the quadrature points.
Private Attributes
size_t d_quadOrder
Order of quadrature point integration approximation.
size_t d_numQuadPts
Number of quadrature points for order d_quadOrder.
size_t d_elemType
Element type.
std::vector< fe::QuadData > d_quads
Quadrature data collection.
Detailed Description
A base class to compute and store quadrature data.
This class provides methods such as quadrature points for integration, shape functions at quadrature points, and derivative of shape functions.
See also:
TriElem, QuadElem
Constructor & Destructor Documentation
fe::BaseElem::BaseElem (size_t order, size_t element_type)
Constructor.
Parameters:
order Order of quadrature point approximation
element_type Type of element in the mesh
Member Function Documentation
virtual std::vector<std::vector<double> > fe::BaseElem::getDerShapes (const util::Point3 & p) [pure virtual]
Returns the values of derivative of shape function.
Parameters:
p Location of point
Returns:
Vector of derivative of shape functions
Implemented in fe::QuadElem, and fe::TriElem.
Referenced by getNumQuadPoints().
size_t fe::BaseElem::getElemType () [inline]
Get element type.
Returns:
type Type of element
size_t fe::BaseElem::getNumQuadPoints () [inline]
Get number of quadrature points in the data.
Returns:
N Number of quadrature points
size_t fe::BaseElem::getQuadOrder () [inline]
Get order of quadrature approximation.
Returns:
order Order of approximation
virtual std::vector<fe::QuadData> fe::BaseElem::getQuadPoints (const std::vector< util::Point3 > & nodes) [pure virtual]
Get vector of quadrature data. Given vertices of an element, where element type is same as what is specified in the constructor of Quadrature class, it returns the vector of quadrature data.
Parameters:
nodes Vector of vertices of an element
Returns:
Vector of QuadData
Implemented in fe::QuadElem, and fe::TriElem.
Referenced by getNumQuadPoints().
virtual std::vector<double> fe::BaseElem::getShapes (const util::Point3 & p) [pure virtual]
Returns the values of shape function at point p.
Parameters:
p Location of point
Returns:
Vector of shape functions at point p
Implemented in fe::QuadElem, and fe::TriElem.
Referenced by getNumQuadPoints().
void fe::BaseElem::init () [private], [pure virtual]
Compute the quadrature points. This must be implemented by inheriting classes.
Implemented in fe::QuadElem, and fe::TriElem.
Referenced by getNumQuadPoints().
virtual double fe::BaseElem::mapRefElemToElem (util::Point3 & p, const std::vector< double > & shapes, const std::vector< std::vector< double >> & der_shapes, const std::vector< util::Point3 > & nodes) [pure virtual]
Maps the point on reference element to given element and returns the determinant of Jacobian.
Parameters:
p Given point in reference element which is to be mapped
shapes Vector shape functions evaluated at the point p
der_shapes Vector of derivative of shape functions at point p
nodes Coordinates of vertices of a given element
Returns:
det(J) Determinant of the Jacobian
Implemented in fe::QuadElem, and fe::TriElem.
Referenced by getNumQuadPoints().
Author
Generated automatically by Doxygen for NLMech from the source code.