.TH "fe::QuadData" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fe::QuadData \- A struct to store the quadrature data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <quadData\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuadData\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBd_w\fP"
.br
.RI "\fI\fBQuadrature\fP weight\&. \fP"
.ti -1c
.RI "\fButil::Point3\fP \fBd_p\fP"
.br
.RI "\fI\fBQuadrature\fP point in 2-d or 3-d\&. \fP"
.ti -1c
.RI "std::vector< double > \fBd_shapes\fP"
.br
.RI "\fIValue of shape functions at quad point p\&. \fP"
.ti -1c
.RI "std::vector< std::vector< double > > \fBd_derShapes\fP"
.br
.RI "\fIValue of derivative of shape functions at quad point p\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A struct to store the quadrature data\&. 
.SH "Field Documentation"
.PP 
.SS "std::vector<std::vector<double> > fe::QuadData::d_derShapes"

.PP
Value of derivative of shape functions at quad point p\&. Size will be the number of vertices the element has\&. E\&.g\&. for triangle element shapes will have three entries\&.
.PP
x-derivative of ith shape function is d_derShapes[i][0]
.PP
y-derivative of ith shape function is d_derShapes[i][1] 
.PP
Referenced by fe::TriElem::init(), and fe::QuadElem::init()\&.
.SS "std::vector<double> fe::QuadData::d_shapes"

.PP
Value of shape functions at quad point p\&. Size will be the number of vertices the element has\&. E\&.g\&. for triangle element shapes will have three entries\&. 
.PP
Referenced by fe::TriElem::init(), and fe::QuadElem::init()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
