fe::QuadElem
NAME
fe::QuadElem - A class for quadrature related operations for bi-linear quadrangle element.
SYNOPSIS
#include <quadElem.h>
Inherits fe::BaseElem.
Public Member Functions
QuadElem (size_t order)
Constructor for quadrangle element.
std::vector< fe::QuadData > getQuadPoints (const std::vector< util::Point3 > &nodes) override
Get vector of quadrature data.
std::vector< double > getShapes (const util::Point3 &p) override
Returns the values of shape function at point p for quadrangle element.
std::vector< std::vector< double > > getDerShapes (const util::Point3 &p) override
Returns the values of derivative of shape function for quadrangle element at point p.
double mapRefElemToElem (util::Point3 &p, const std::vector< double > &shapes, const std::vector< std::vector< double >> &der_shapes, const std::vector< util::Point3 > &nodes) override
Maps the point on reference quadrangle to given quadrangle and returns determinant of Jacobian.
Private Member Functions
Internal methods for triangle element
void init () override
Compute the quadrature points for triangle element.
Detailed Description
A class for quadrature related operations for bi-linear quadrangle element.
This class provides methods such as quadrature points for integration, shape functions at quadrature points, and derivative of shape functions. They are specific to linear quadrangle element.
The reference quadrangle element is made of four vertex at point $ (-1,-1), \, (1,-1), \, (1,1), \, (-1,1) $.
Constructor & Destructor Documentation
fe::QuadElem::QuadElem (size_t order) [explicit]
Constructor for quadrangle element.
Parameters:
order Order of quadrature point approximation
Member Function Documentation
std::vector< std::vector< double > > fe::QuadElem::getDerShapes (const util::Point3 & p) [override], [virtual]
Returns the values of derivative of shape function for quadrangle element at point p. For bi-linear quadrangle element, derivative of shape functions are linear and are as follows (for reference quadrangle)
\[\frac{d N_1(\xi, \ta)}{d\xi} = \frac{-(1 - \ta)}{4}, \, \frac{d N_1 (\xi, \ta)}{d\ta} = \frac{-(1 - \xi)}{4}, \] \[\frac{d N_2(\xi, \ta)}{d\xi} = \frac{(1 - \ta)}{4}, \, \frac{d N_2 (\xi, \ta)}{d\ta} = \frac{-(1 + \xi)}{4}, \] \[\frac{d N_3(\xi, \ta)}{d\xi} = \frac{(1 + \ta)}{4}, \, \frac{d N_3 (\xi, \ta)}{d\ta} = \frac{(1 + \xi)}{4}, \] \[\frac{d N_4(\xi, \ta)}{d\xi} = \frac{-(1 + \ta)}{4}, \, \frac{d N_4 (\xi, \ta)}{d\ta} = \frac{(1 - \xi)}{4}. \]
Parameters:
p Point at which derivatives are to be evaluated
Returns:
Vector of derivative of shape functions
Implements fe::BaseElem.
Referenced by init().
std::vector< fe::QuadData > fe::QuadElem::getQuadPoints (const std::vector< util::Point3 > & nodes) [override], [virtual]
Get vector of quadrature data. Given vertices of an element, where element type is same as what is specified in the constructor of Quadrature class, it returns the vector of quadrature data.
Parameters:
nodes Vector of vertices of an element
Returns:
Vector of QuadData
Implements fe::BaseElem.
std::vector< double > fe::QuadElem::getShapes (const util::Point3 & p) [override], [virtual]
Returns the values of shape function at point p for quadrangle element. Quadrangle assumed is a reference quadrangle with vertices v1 = (-1,-1), v2 =(1,-1), v3 = (1,1), v4 = (-1,1). The shape function for the reference quadrangle is given by \[N_1(\xi, \ta) = \frac{(1- \xi)(1 - \ta)}{4}, \, N_2(\xi, \ta) = \frac{(1+ \xi)(1 - \ta)}{4}, \] \[ N_3(\xi, \ta) = \frac{(1+ \xi)(1 + \ta)}{4}, N_4(\xi, \ta) = \frac{(1- \xi)(1 + \ta)}{4}. \]
Parameters:
p Location of point
Returns:
Vector of shape functions at point p
Implements fe::BaseElem.
Referenced by init().
double fe::QuadElem::mapRefElemToElem (util::Point3 & p, const std::vector< double > & shapes, const std::vector< std::vector< double >> & der_shapes, const std::vector< util::Point3 > & nodes) [override], [virtual]
Maps the point on reference quadrangle to given quadrangle and returns determinant of Jacobian. For linear triangle element, the map from $ (\xi, \ta) $ to $ (x,y) $ coordinate is given by \[ x = N_1(\xi, \ta) x_1 + N_2(\xi, \ta) x_2 + N_3(\xi, \ta) x_3,\] \[ y = N_1(\xi, \ta) y_1 + N_2(\xi, \ta) y_2 + N_3(\xi, \ta) y_3,\] where $ N_1, N_2, N_3 $ are described in getTriShapes() and $ (x_1, y_1), (x_2,y_2), (x_3,y_3) $ are vertices of given triangle.
Jacobian of this map is a matrix \[ J = [\frac{dx}{d\xi},\frac{dy}{d\xi}; \frac{dx}{d\ta}, \frac{dy}{d\ta}] \] and determinant of Jacobian is \[ det(J) = \frac{dx}{d\xi} \times \frac{dy}{d\ta} - \frac{dy}{d\xi}\times \frac{dx}{d\ta}. \]
It can be easily checked than for linear triangle elements, we simply have \[ \frac{dx}{d\xi} = x_2 - x_1, \frac{dx}{d\ta} = x_3 - x_1, \] \[ \frac{dy}{d\xi} = y_2 - y_1, \frac{dy}{d\ta} = y_3 - y_1. \] Therefore, \[ det(J) = (x_2 - x_1)(y_3 - y_1) - (y_2 - y_1)(x_3 - x_1).\]
Parameters:
p Given point in reference triangle which is to be mapped
shapes Vector shape functions evaluated at the point p
der_shapes Vector of derivative of shape functions at point p
nodes Coordinates of vertices of a given element *
Returns:
det(J) Determinant of the Jacobian
Implements fe::BaseElem.
Referenced by getQuadPoints().
Author
Generated automatically by Doxygen for NLMech from the source code.