.TH "fe::TriElem" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fe::TriElem \- A class for quadrature related operations for linear triangle element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <triElem\&.h>\fP
.PP
Inherits \fBfe::BaseElem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriElem\fP (size_t order)"
.br
.RI "\fIConstructor for triangle element\&. \fP"
.ti -1c
.RI "std::vector< \fBfe::QuadData\fP > \fBgetQuadPoints\fP (const std::vector< \fButil::Point3\fP > &nodes) override"
.br
.RI "\fIGet vector of quadrature data\&. \fP"
.ti -1c
.RI "std::vector< double > \fBgetShapes\fP (const \fButil::Point3\fP &p) override"
.br
.RI "\fIReturns the values of shape function at point p for triangle element\&. \fP"
.ti -1c
.RI "std::vector< std::vector< double > > \fBgetDerShapes\fP (const \fButil::Point3\fP &p) override"
.br
.RI "\fIReturns the values of derivative of shape function for triangle element\&. \fP"
.ti -1c
.RI "double \fBmapRefElemToElem\fP (\fButil::Point3\fP &p, const std::vector< double > &shapes, const std::vector< std::vector< double >> &der_shapes, const std::vector< \fButil::Point3\fP > &nodes) override"
.br
.RI "\fIMaps the point on reference triangle to given triangle and returns determinant of Jacobian\&. \fP"
.in -1c
.SS "Private Member Functions"

.PP
.RI "\fBInternal methods for triangle element\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBinit\fP () override"
.br
.RI "\fICompute the quadrature points for triangle element\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
A class for quadrature related operations for linear triangle element\&. 

This class provides methods such as quadrature points for integration, shape functions at quadrature points, and derivative of shape functions\&. They are specific to linear triangle element\&.
.PP
The reference triangle element is made of three vertex at point $ (0,0), \, (1,0), \, (0,1) $\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fe::TriElem::TriElem (size_t order)\fC [explicit]\fP"

.PP
Constructor for triangle element\&. 
.PP
\fBParameters:\fP
.RS 4
\fIorder\fP Order of quadrature point approximation 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::vector< double > > fe::TriElem::getDerShapes (const \fButil::Point3\fP & p)\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns the values of derivative of shape function for triangle element\&. For linear triangle element, derivative of shape functions are constant and are as follows (for reference triangle)
.PP
\[\frac{d N_1(\xi, \eta)}{d\xi} = -1, \, \frac{d N_1(\xi, \eta)}{d\eta} = -1, \] \[\frac{d N_2(\xi, \eta)}{d\xi} = 1, \, \frac{d N_2(\xi, \eta)}{d\eta} = 0, \] \[\frac{d N_3(\xi, \eta)}{d\xi} = 0, \, \frac{d N_3(\xi, \eta)}{d\eta} = 1. \]
.PP
\fBParameters:\fP
.RS 4
\fIp\fP Location of point 
.RE
.PP
\fBReturns:\fP
.RS 4
Vector of derivative of shape functions 
.RE
.PP

.PP
Implements \fBfe::BaseElem\fP\&.
.PP
Referenced by init()\&.
.SS "std::vector< \fBfe::QuadData\fP > fe::TriElem::getQuadPoints (const std::vector< \fButil::Point3\fP > & nodes)\fC [override]\fP, \fC [virtual]\fP"

.PP
Get vector of quadrature data\&. Given vertices of an element, where element type is same as what is specified in the constructor of \fBQuadrature\fP class, it returns the vector of quadrature data\&.
.PP
\fBParameters:\fP
.RS 4
\fInodes\fP Vector of vertices of an element 
.RE
.PP
\fBReturns:\fP
.RS 4
Vector of \fBQuadData\fP 
.RE
.PP

.PP
Implements \fBfe::BaseElem\fP\&.
.SS "std::vector< double > fe::TriElem::getShapes (const \fButil::Point3\fP & p)\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns the values of shape function at point p for triangle element\&. Triangle assumed is a reference triangle with vertices v1 = (0,0), v2 = (1,0), v3 = (0,1)\&. The shape function for the reference triangle is given by \[N_1(\xi, \eta) = 1- \xi - \eta, \, N_2(\xi, \eta) = \xi, \, N_3(\xi, \eta) = \eta. \]
.PP
\fBParameters:\fP
.RS 4
\fIp\fP Location of point 
.RE
.PP
\fBReturns:\fP
.RS 4
Vector of shape functions at point p 
.RE
.PP

.PP
Implements \fBfe::BaseElem\fP\&.
.PP
Referenced by init()\&.
.SS "double fe::TriElem::mapRefElemToElem (\fButil::Point3\fP & p, const std::vector< double > & shapes, const std::vector< std::vector< double >> & der_shapes, const std::vector< \fButil::Point3\fP > & nodes)\fC [override]\fP, \fC [virtual]\fP"

.PP
Maps the point on reference triangle to given triangle and returns determinant of Jacobian\&. For linear triangle element, the map from $ (\xi, \eta) $ to $ (x,y) $ coordinate is given by \[ x = N_1(\xi, \eta) x_1 + N_2(\xi, \eta) x_2 + N_3(\xi, \eta) x_3,\] \[ y = N_1(\xi, \eta) y_1 + N_2(\xi, \eta) y_2 + N_3(\xi, \eta) y_3,\] where $ N_1, N_2, N_3 $ are described in getTriShapes() and $ (x_1, y_1), (x_2,y_2), (x_3,y_3) $ are vertices of given triangle\&.
.PP
Jacobian of this map is a matrix \[ J = [\frac{dx}{d\xi},\frac{dy}{d\xi}; \frac{dx}{d\eta}, \frac{dy}{d\eta}] \] and determinant of Jacobian is \[ det(J) = \frac{dx}{d\xi} \times \frac{dy}{d\eta} - \frac{dy}{d\xi}\times \frac{dx}{d\eta}. \]
.PP
It can be easily checked than for linear triangle elements, we simply have \[ \frac{dx}{d\xi} = x_2 - x_1, \frac{dx}{d\eta} = x_3 - x_1, \] \[ \frac{dy}{d\xi} = y_2 - y_1, \frac{dy}{d\eta} = y_3 - y_1. \] Therefore, \[ det(J) = (x_2 - x_1)(y_3 - y_1) - (y_2 - y_1)(x_3 - x_1).\]
.PP
\fBParameters:\fP
.RS 4
\fIp\fP Given point in reference triangle which is to be mapped 
.br
\fIshapes\fP Vector shape functions evaluated at the point p 
.br
\fIder_shapes\fP Vector of derivative of shape functions at point p 
.br
\fInodes\fP Coordinates of vertices of a given element * 
.RE
.PP
\fBReturns:\fP
.RS 4
det(J) Determinant of the Jacobian 
.RE
.PP

.PP
Implements \fBfe::BaseElem\fP\&.
.PP
Referenced by getQuadPoints()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
