.TH "geometry" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometry \- Collection of methods and database related to geometry\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFracture\fP"
.br
.RI "\fIA class for fracture state of bonds\&. \fP"
.ti -1c
.RI "class \fBInteriorFlags\fP"
.br
.RI "\fIA class to store interior/exterior flags of node\&. \fP"
.ti -1c
.RI "class \fBNeighbor\fP"
.br
.RI "\fIA class to store neighbor list and provide access to the list\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of methods and database related to geometry\&. 

This namespace provides methods and data members specific to geometry\&. It consists of class \fBFracture\fP, \fBInteriorFlags\fP, and \fBNeighbor\fP\&.
.PP
\fBSee also:\fP
.RS 4
\fBFracture\fP, \fBInteriorFlags\fP, \fBNeighbor\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
