.TH "inp::MassMatrixDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::MassMatrixDeck \- Structure to read and store mass matrix related input data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <massMatrixDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMassMatrixDeck\fP ()=default"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "std::string \fBd_MApproxType\fP"
.br
.RI "\fIMass matrix approximation type\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store mass matrix related input data\&. 
.SH "Field Documentation"
.PP 
.SS "std::string inp::MassMatrixDeck::d_MApproxType"

.PP
Mass matrix approximation type\&. List of allowed values are:
.IP "\(bu" 2
\fIexact\fP -- no approximation
.IP "\(bu" 2
\fIlumped\fP -- lumping of mass matrix 
.PP

.PP
Referenced by fe::MassMatrix::MassMatrix(), and inp::Input::setMassMatrixDeck()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
