.TH "inp::Policy" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::Policy \- A class to enforce certain policies to reduce memory loads\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <policy\&.h>\fP
.SS "Public Member Functions"

.PP
.RI "\fBSetter method\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBaddToTags\fP (size_t level, const std::string &tag)"
.br
.RI "\fIAdds tag to specified level tag list\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBGetter method\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "bool \fBpopulateData\fP (const std::string &tag)"
.br
.RI "\fIReturns true/false depending on whether tag is found\&. \fP"
.ti -1c
.RI "int \fBgetMemoryControlFlag\fP ()"
.br
.RI "\fIReturns memory control flag\&. \fP"
.in -1c
.in -1c
.SS "Static Public Member Functions"

.PP
.RI "\fBGet and destroy instance\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static \fBPolicy\fP * \fBgetInstance\fP ()"
.br
.RI "\fIReturns the pointer to static class\&. Creates instance in its first call\&. \fP"
.ti -1c
.RI "static \fBPolicy\fP * \fBgetInstance\fP (\fBinp::PolicyDeck\fP *deck)"
.br
.RI "\fIReturns the pointer to static class\&. Creates instance in its first call\&. \fP"
.ti -1c
.RI "static void \fBdestroyInstance\fP ()"
.br
.RI "\fIDestroys the instance\&. \fP"
.in -1c
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBPolicy\fP ()"
.br
.RI "\fIPrivate constructor\&. \fP"
.ti -1c
.RI "\fBPolicy\fP (\fBinp::PolicyDeck\fP *deck)"
.br
.RI "\fIPrivate constructor\&. \fP"
.ti -1c
.RI "\fBPolicy\fP (\fBPolicy\fP const &)"
.br
.RI "\fIPrivate operator\&. \fP"
.ti -1c
.RI "const \fBPolicy\fP & \fBoperator=\fP (const \fBPolicy\fP &)"
.br
.RI "\fIPrivate operator\&. \fP"
.ti -1c
.RI "\fB~Policy\fP ()"
.br
.RI "\fIPrivate destructor\&. \fP"
.in -1c
.PP
.RI "\fBPrivate methods\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "\fIInitializes the data\&. \fP"
.in -1c
.in -1c
.SS "Internal data"

.in +1c
.ti -1c
.RI "static \fBPolicy\fP * \fBd_instance_p\fP = nullptr"
.br
.RI "\fIStatic instance of \fBPolicy\fP class\&. \fP"
.ti -1c
.RI "\fBinp::PolicyDeck\fP * \fBd_policyDeck_p\fP"
.br
.RI "\fI\fBPolicy\fP deck which contains input data\&. \fP"
.ti -1c
.RI "std::vector< std::string > \fBd_l0Tags\fP"
.br
.RI "\fIList of variable names in different levels to help enforce the memory control\&. \fP"
.ti -1c
.RI "std::vector< std::string > \fBd_l1Tags\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBd_l2Tags\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBd_otherTags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to enforce certain policies to reduce memory loads\&. 

This class introduces policies which restrict population (declaration) of post-processing data which are not important for running simulation and are postprocessing data\&.
.PP
For example, if the simulation is large, this class will restrict population of data such as fracture energy, damage data, strain and stress data, etc\&.
.PP
This class also enforces lumping approximation of mass matrix if the level of restriction is set to 2 or higher\&.
.PP
The level of memory restriction can be set in the input file\&. Default value is 0 which means no restriction\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "inp::Policy::Policy (\fBinp::PolicyDeck\fP * deck)\fC [private]\fP"

.PP
Private constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdeck\fP \fBInput\fP deck which contains user-specified information 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void inp::Policy::addToTags (size_t level, const std::string & tag)"

.PP
Adds tag to specified level tag list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP Level of tag list 
.br
\fItag\fP Tag to be appended to list 
.RE
.PP

.PP
Referenced by model::FDModel::init(), and fe::Mesh::Mesh()\&.
.SS "\fBinp::Policy\fP * inp::Policy::getInstance (\fBinp::PolicyDeck\fP * deck)\fC [static]\fP"

.PP
Returns the pointer to static class\&. Creates instance in its first call\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdeck\fP \fBInput\fP deck which contains user-specified information 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPolicy\fP instance of static class \fBPolicy\fP 
.RE
.PP

.SS "int inp::Policy::getMemoryControlFlag ()"

.PP
Returns memory control flag\&. 
.PP
\fBReturns:\fP
.RS 4
Flag 
.RE
.PP

.SS "bool inp::Policy::populateData (const std::string & tag)"

.PP
Returns true/false depending on whether tag is found\&. 
.PP
\fBParameters:\fP
.RS 4
\fItag\fP Tag to search for 
.RE
.PP
\fBReturns:\fP
.RS 4
True/False 
.RE
.PP

.PP
Referenced by fe::Mesh::createData(), and model::FDModel::init()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
