.TH "inp::ModelDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::ModelDeck \- Structure to read and store model related data input\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modelDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelDeck\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "std::string \fBd_simType\fP"
.br
.RI "\fISimulation type\&. \fP"
.ti -1c
.RI "std::string \fBd_spatialDiscretization\fP"
.br
.RI "\fITag for spatial discretization\&. \fP"
.ti -1c
.RI "std::string \fBd_timeDiscretization\fP"
.br
.RI "\fITag for time discretization\&. \fP"
.ti -1c
.RI "size_t \fBd_dim\fP"
.br
.RI "\fIDimension\&. \fP"
.ti -1c
.RI "double \fBd_tFinal\fP"
.br
.RI "\fIFinal simulation time\&. \fP"
.ti -1c
.RI "double \fBd_dt\fP"
.br
.RI "\fISize of time steps\&. \fP"
.ti -1c
.RI "size_t \fBd_Nt\fP"
.br
.RI "\fINumber of time steps\&. \fP"
.ti -1c
.RI "double \fBd_horizon\fP"
.br
.RI "\fIHorizon\&. \fP"
.ti -1c
.RI "int \fBd_rh\fP"
.br
.RI "\fIRatio of Horizon to mesh size\&. \fP"
.ti -1c
.RI "double \fBd_h\fP"
.br
.RI "\fIMesh size\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store model related data input\&. 
.SH "Field Documentation"
.PP 
.SS "int inp::ModelDeck::d_rh"

.PP
Ratio of Horizon to mesh size\&. E\&.g\&. ratio = 4 means mesh size is 1/4th of horizon\&. 
.PP
Referenced by inp::Input::setModelDeck()\&.
.SS "std::string inp::ModelDeck::d_simType"

.PP
Simulation type\&. List of allowed values are:
.IP "\(bu" 2
\fIexplicit\fP 
.IP "\(bu" 2
\fIimplicit\fP 
.PP

.PP
Referenced by inp::Input::setModelDeck()\&.
.SS "std::string inp::ModelDeck::d_spatialDiscretization"

.PP
Tag for spatial discretization\&. List of allowed values are:
.IP "\(bu" 2
\fIfinite_difference\fP 
.IP "\(bu" 2
\fIweak_finite_element\fP 
.IP "\(bu" 2
\fInodal_finite_element\fP 
.IP "\(bu" 2
\fItruss_finite_element\fP 
.PP

.PP
Referenced by inp::Input::getSpatialDiscretization(), and inp::Input::setModelDeck()\&.
.SS "std::string inp::ModelDeck::d_timeDiscretization"

.PP
Tag for time discretization\&. List of allowed values are:
.IP "\(bu" 2
'' -- none
.IP "\(bu" 2
\fIcentral_difference\fP 
.IP "\(bu" 2
\fIvelocity_verlet\fP 
.PP

.PP
Referenced by inp::Input::setModelDeck()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
