.TH "inp::SolverDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::SolverDeck \- Structure to read and store solver related input data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <solverDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolverDeck\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "std::string \fBd_solverType\fP"
.br
.RI "\fISolver type\&. \fP"
.ti -1c
.RI "int \fBd_maxIters\fP"
.br
.RI "\fIMaximum iterations\&. \fP"
.ti -1c
.RI "double \fBd_tol\fP"
.br
.RI "\fITolerance\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store solver related input data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
