.TH "inp::QuadratureDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::QuadratureDeck \- Structure to read and store quadrature point related input data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <quadratureDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuadratureDeck\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "size_t \fBd_quadOrder\fP"
.br
.RI "\fIOrder of quadrature point integration approximation\&. \fP"
.ti -1c
.RI "size_t \fBd_quadOrderM\fP"
.br
.RI "\fIOrder of quadrature point integration approximation for mass matrix\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store quadrature point related input data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
