.TH "inp::InitialConditionDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::InitialConditionDeck \- Structure to read and store policy data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <initialConditionDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInitialConditionDeck\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBinp::ICData\fP \fBd_uICData\fP"
.br
.RI "\fIInitial condition data for displacement\&. \fP"
.ti -1c
.RI "\fBinp::ICData\fP \fBd_vICData\fP"
.br
.RI "\fIInitial condition data for velocity\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store policy data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
