inp::Policy
NAME
inp::Policy - A class to enforce certain policies to reduce memory loads.
SYNOPSIS
#include <policy.h>
Public Member Functions
Setter method
void addToTags (size_t level, const std::string &tag)
Adds tag to specified level tag list.
Getter method
bool populateData (const std::string &tag)
Returns true/false depending on whether tag is found.
int getMemoryControlFlag ()
Returns memory control flag.
Static Public Member Functions
Get and destroy instance
static Policy * getInstance ()
Returns the pointer to static class. Creates instance in its first call.
static Policy * getInstance (inp::PolicyDeck *deck)
Returns the pointer to static class. Creates instance in its first call.
static void destroyInstance ()
Destroys the instance.
Private Member Functions
Policy ()
Private constructor.
Policy (inp::PolicyDeck *deck)
Private constructor.
Policy (Policy const &)
Private operator.
const Policy & operator= (const Policy &)
Private operator.
~Policy ()
Private destructor.
Private methods
void init ()
Initializes the data.
Internal data
static Policy * d_instance_p = nullptr
Static instance of Policy class.
inp::PolicyDeck * d_policyDeck_p
Policy deck which contains input data.
std::vector< std::string > d_l0Tags
List of variable names in different levels to help enforce the memory control.
std::vector< std::string > d_l1Tags
std::vector< std::string > d_l2Tags
std::vector< std::string > d_otherTags
Detailed Description
A class to enforce certain policies to reduce memory loads.
This class introduces policies which restrict population (declaration) of post-processing data which are not important for running simulation and are postprocessing data.
For example, if the simulation is large, this class will restrict population of data such as fracture energy, damage data, strain and stress data, etc.
This class also enforces lumping approximation of mass matrix if the level of restriction is set to 2 or higher.
The level of memory restriction can be set in the input file. Default value is 0 which means no restriction.
Constructor & Destructor Documentation
inp::Policy::Policy (inp::PolicyDeck * deck) [private]
Private constructor.
Parameters:
deck Input deck which contains user-specified information
Member Function Documentation
void inp::Policy::addToTags (size_t level, const std::string & tag)
Adds tag to specified level tag list.
Parameters:
level Level of tag list
tag Tag to be appended to list
Referenced by model::FDModel::init(), and fe::Mesh::Mesh().
inp::Policy * inp::Policy::getInstance (inp::PolicyDeck * deck) [static]
Returns the pointer to static class. Creates instance in its first call.
Parameters:
deck Input deck which contains user-specified information
Returns:
Policy instance of static class Policy
int inp::Policy::getMemoryControlFlag ()
Returns memory control flag.
Returns:
Flag
bool inp::Policy::populateData (const std::string & tag)
Returns true/false depending on whether tag is found.
Parameters:
tag Tag to search for
Returns:
True/False
Referenced by fe::Mesh::createData(), and model::FDModel::init().
Author
Generated automatically by Doxygen for NLMech from the source code.