.TH "inp::InteriorFlagsDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::InteriorFlagsDeck \- Structure to read and store interior flags (no-fail region)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interiorFlagsDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInteriorFlagsDeck\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "bool \fBd_noFailActive\fP"
.br
.RI "\fIFlag which indicates if no-fail region is active\&. \fP"
.ti -1c
.RI "double \fBd_noFailTol\fP"
.br
.RI "\fITolerance to decide if the point is in interior/exterior\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store interior flags (no-fail region) 

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
