.TH "inp::MatData" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::MatData \- Structure for elastic properties and fracture properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <materialDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatData\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.PP
.RI "\fBConversion methods\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "double \fBtoE\fP (double K, double nu)"
.br
.RI "\fICompute Young's modulus E from Bulk modulus K and Poisson's ratio nu\&. \fP"
.ti -1c
.RI "double \fBtoK\fP (double E, double nu)"
.br
.RI "\fICompute Bulk modulus K from Young's modulus K and Poisson's ratio nu\&. \fP"
.ti -1c
.RI "double \fBtoLambdaE\fP (double E, double nu)"
.br
.RI "\fICompute Lame first parameter lambda from Young's modulus K and Poisson's ratio nu\&. \fP"
.ti -1c
.RI "double \fBtoLambdaK\fP (double K, double nu)"
.br
.RI "\fICompute Lame first parameter lambda from Bulk modulus K and Poisson's ratio nu\&. \fP"
.ti -1c
.RI "double \fBtoGc\fP (double KIc, double nu, double E)"
.br
.RI "\fICompute critical energy release rate Gc from critical stress-intensity factor KIc, Poisson's ratio nu, and Young's modulus E\&. \fP"
.ti -1c
.RI "double \fBtoKIc\fP (double Gc, double nu, double E)"
.br
.RI "\fICompute critical stress-intensity factor KIc from critical energy release rate Gc, Poisson's ratio nu, and Young's modulus E\&. \fP"
.in -1c
.in -1c
.SS "Data Fields"

.PP
.RI "\fBElastic material properties\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "double \fBd_E\fP"
.br
.RI "\fIYoung's elastic modulus\&. \fP"
.ti -1c
.RI "double \fBd_G\fP"
.br
.RI "\fIShear modulus or Lame second parameter\&. \fP"
.ti -1c
.RI "double \fBd_K\fP"
.br
.RI "\fIBulk modulus\&. \fP"
.ti -1c
.RI "double \fBd_nu\fP"
.br
.RI "\fIPoisson's ratio\&. \fP"
.ti -1c
.RI "double \fBd_lambda\fP"
.br
.RI "\fILame first parameter\&. \fP"
.ti -1c
.RI "double \fBd_mu\fP"
.br
.RI "\fILame second parameter\&. \fP"
.in -1c
.in -1c
.PP
.RI "\fBFracture properties\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "double \fBd_KIc\fP"
.br
.RI "\fICritical stress intensity factor\&. \fP"
.ti -1c
.RI "double \fBd_Gc\fP"
.br
.RI "\fICritical energy release rate\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure for elastic properties and fracture properties\&. 
.SH "Member Function Documentation"
.PP 
.SS "double inp::MatData::toE (double K, double nu)\fC [inline]\fP"

.PP
Compute Young's modulus E from Bulk modulus K and Poisson's ratio nu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIK\fP Bulk modulus 
.br
\fInu\fP Poisson's ratio 
.RE
.PP
\fBReturns:\fP
.RS 4
E Young's modulus 
.RE
.PP

.SS "double inp::MatData::toGc (double KIc, double nu, double E)\fC [inline]\fP"

.PP
Compute critical energy release rate Gc from critical stress-intensity factor KIc, Poisson's ratio nu, and Young's modulus E\&. 
.PP
\fBParameters:\fP
.RS 4
\fIKIc\fP Critical stress-intensity factor 
.br
\fInu\fP Poisson's ratio 
.br
\fIE\fP Young's modulus 
.RE
.PP
\fBReturns:\fP
.RS 4
Gc Critical energy release rate 
.RE
.PP

.SS "double inp::MatData::toK (double E, double nu)\fC [inline]\fP"

.PP
Compute Bulk modulus K from Young's modulus K and Poisson's ratio nu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIE\fP Young's modulus 
.br
\fInu\fP Poisson's ratio 
.RE
.PP
\fBReturns:\fP
.RS 4
K Bulk modulus 
.RE
.PP

.SS "double inp::MatData::toKIc (double Gc, double nu, double E)\fC [inline]\fP"

.PP
Compute critical stress-intensity factor KIc from critical energy release rate Gc, Poisson's ratio nu, and Young's modulus E\&. 
.PP
\fBParameters:\fP
.RS 4
\fIGc\fP Critical energy release rate 
.br
\fInu\fP Poisson's ratio 
.br
\fIE\fP Young's modulus 
.RE
.PP
\fBReturns:\fP
.RS 4
KIc Critical stress-intensity factor 
.RE
.PP

.SS "double inp::MatData::toLambdaE (double E, double nu)\fC [inline]\fP"

.PP
Compute Lame first parameter lambda from Young's modulus K and Poisson's ratio nu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIE\fP Young's modulus 
.br
\fInu\fP Poisson's ratio 
.RE
.PP
\fBReturns:\fP
.RS 4
lambda Lame first parameter 
.RE
.PP

.SS "double inp::MatData::toLambdaK (double K, double nu)\fC [inline]\fP"

.PP
Compute Lame first parameter lambda from Bulk modulus K and Poisson's ratio nu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIK\fP Bulk modulus 
.br
\fInu\fP Poisson's ratio 
.RE
.PP
\fBReturns:\fP
.RS 4
lambda Lame first parameter 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
