.TH "inp::EdgeCrack" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::EdgeCrack \- A structure to edge crack of any orientation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fractureDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdgeCrack\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int \fBd_o\fP"
.br
.RI "\fIOrientation of crack\&. \fP"
.ti -1c
.RI "double \fBd_theta\fP"
.br
.RI "\fIAngle the edge crack makes with the horizontal axis\&. \fP"
.ti -1c
.RI "double \fBd_l\fP"
.br
.RI "\fITotal current length of crack\&. \fP"
.ti -1c
.RI "double \fBd_lt\fP"
.br
.RI "\fICurrent length of crack on top side (right side) \fP"
.ti -1c
.RI "double \fBd_lb\fP"
.br
.RI "\fICurrent length of crack on bottom side (left side) \fP"
.ti -1c
.RI "std::vector< double > \fBd_vt\fP"
.br
.RI "\fIVelocity of top (right) crack tip\&. \fP"
.ti -1c
.RI "std::vector< double > \fBd_vb\fP"
.br
.RI "\fIVelocity of bottom (left) crack tip\&. \fP"
.ti -1c
.RI "int \fBd_it\fP"
.br
.RI "\fIClosest id of node to top (right) crack tip\&. \fP"
.ti -1c
.RI "int \fBd_ib\fP"
.br
.RI "\fIClosest id of node to bottom (left) crack tip\&. \fP"
.ti -1c
.RI "int \fBd_iot\fP"
.br
.RI "\fIClosest id of node to old top (right) crack tip\&. \fP"
.ti -1c
.RI "int \fBd_iob\fP"
.br
.RI "\fIClosest id of node to old bottom (left) crack tip\&. \fP"
.ti -1c
.RI "std::vector< double > \fBd_pt\fP"
.br
.RI "\fITop (right) crack tip location\&. \fP"
.ti -1c
.RI "std::vector< double > \fBd_pb\fP"
.br
.RI "\fIBottom (left) crack tip location\&. \fP"
.ti -1c
.RI "std::vector< double > \fBd_pot\fP"
.br
.RI "\fIOld top (right) crack tip location\&. \fP"
.ti -1c
.RI "std::vector< double > \fBd_pob\fP"
.br
.RI "\fIOld bottom (left) crack tip location\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
A structure to edge crack of any orientation\&. 
.SH "Field Documentation"
.PP 
.SS "int inp::EdgeCrack::d_o"

.PP
Orientation of crack\&. 
.IP "\(bu" 2
1 for orientation along horizontal axis (x-axis),
.IP "\(bu" 2
-1 for orientation along vertical axis (y-axis),
.IP "\(bu" 2
0 for any crack which makes nonzero angle with the horizontal axis 
.PP

.PP
Referenced by inp::Input::setFractureDeck()\&.
.SS "double inp::EdgeCrack::d_theta"

.PP
Angle the edge crack makes with the horizontal axis\&. 
.IP "\(bu" 2
0 if orientation = 1,
.IP "\(bu" 2
$ \pi/2 $ if orientation = -1
.IP "\(bu" 2
Value for orientation = 0 
.PP

.PP
Referenced by inp::Input::setFractureDeck()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
