.TH "inp::PolicyDeck" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inp::PolicyDeck \- Structure to read and store policy related input data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <policyDeck\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolicyDeck\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int \fBd_memControlFlag\fP"
.br
.RI "\fIFlag which indicates level of memory control to be enforced\&. \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Structure to read and store policy related input data\&. 
.SH "Field Documentation"
.PP 
.SS "int inp::PolicyDeck::d_memControlFlag"

.PP
Flag which indicates level of memory control to be enforced\&. Default is 0 which means no control\&. Max at present is 2 which means as much control as possible\&. 
.PP
Referenced by inp::Policy::getMemoryControlFlag(), inp::Policy::Policy(), inp::Policy::populateData(), and inp::Input::setPolicyDeck()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
