.TH "Input" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Input \- Input
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBinp::Input\fP"
.br
.RI "\fIA class to read input file\&. \fP"
.ti -1c
.RI "struct \fBinp::FractureDeck\fP"
.br
.RI "\fIStructure to read and store fracture related input data\&. \fP"
.ti -1c
.RI "struct \fBinp::InitialConditionDeck\fP"
.br
.RI "\fIStructure to read and store policy data\&. \fP"
.ti -1c
.RI "struct \fBinp::InteriorFlagsDeck\fP"
.br
.RI "\fIStructure to read and store interior flags (no-fail region) \fP"
.ti -1c
.RI "struct \fBinp::LoadingDeck\fP"
.br
.RI "\fIStructure to read and store policy data\&. \fP"
.ti -1c
.RI "struct \fBinp::MassMatrixDeck\fP"
.br
.RI "\fIStructure to read and store mass matrix related input data\&. \fP"
.ti -1c
.RI "struct \fBinp::MaterialDeck\fP"
.br
.RI "\fIStructure to read and store material related data\&. \fP"
.ti -1c
.RI "struct \fBinp::MeshDeck\fP"
.br
.RI "\fIStructure to read and store mesh related input data\&. \fP"
.ti -1c
.RI "struct \fBinp::ModelDeck\fP"
.br
.RI "\fIStructure to read and store model related data input\&. \fP"
.ti -1c
.RI "struct \fBinp::NeighborDeck\fP"
.br
.RI "\fIStructure to read and store neighbor list related input data\&. \fP"
.ti -1c
.RI "struct \fBinp::OutputDeck\fP"
.br
.RI "\fIStructure to read and store output data\&. \fP"
.ti -1c
.RI "struct \fBinp::PolicyDeck\fP"
.br
.RI "\fIStructure to read and store policy related input data\&. \fP"
.ti -1c
.RI "struct \fBinp::QuadratureDeck\fP"
.br
.RI "\fIStructure to read and store quadrature point related input data\&. \fP"
.ti -1c
.RI "struct \fBinp::SolverDeck\fP"
.br
.RI "\fIStructure to read and store solver related input data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Group which reads and stores input data 
.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
