.TH "loading::Loading" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loading::Loading \- A class to apply displacement and force boundary condition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loading\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoading\fP (\fBinp::LoadingDeck\fP *deck)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class to apply displacement and force boundary condition\&. 

In this class we process input data and apply complex boundary condition\&. The boundary conditions can be specified in multiple sets, and in each set one can specify the region where the boundary condition is to be applied, and the type of function to be used\&.
.PP
This class also provides method to set the fixity of nodes as fixed if the displacement is specified on the dof of the node\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "loading::Loading::Loading (\fBinp::LoadingDeck\fP * deck)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdeck\fP Input deck which contains user-specified information 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
