.TH "loading::InitialCondition" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loading::InitialCondition \- A class to apply initial condition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <initialCondition\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInitialCondition\fP (\fBinp::InitialConditionDeck\fP *deck)"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class to apply initial condition\&. 

This class processes input data and provides method to apply initial condition\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "loading::InitialCondition::InitialCondition (\fBinp::InitialConditionDeck\fP * deck)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdeck\fP Input deck which contains user-specified information 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
