.TH "material::Material" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
material::Material \- A class to model a peridynamic material\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <material\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterial\fP (\fBinp::MaterialDeck\fP *deck)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "bool \fBisStateActive\fP ()"
.br
.RI "\fIReturns true if state-based potential is active\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class to model a peridynamic material\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "material::Material::Material (\fBinp::MaterialDeck\fP * deck)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdeck\fP Input deck which contains user-specified information 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool material::Material::isStateActive ()"

.PP
Returns true if state-based potential is active\&. 
.PP
\fBReturns:\fP
.RS 4
True/false 
.RE
.PP

.PP
Referenced by model::FDModel::init()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
