.TH "material" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
material \- Collection of methods and database related to material\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMaterial\fP"
.br
.RI "\fIA class to model a peridynamic material\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of methods and database related to material\&. 

This namespace provides collection of different materials within the Peridynamics theory\&.
.PP
At present we have implemented state-based model which can also simulate bond-based model\&. We consider \fBRNP\fP regularized potential as well \fBPMB\fP material\&.
.PP
\fBSee also:\fP
.RS 4
\fBMaterial\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
