.TH "model" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model \- Collection of Peridynamic models\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFDModel\fP"
.br
.RI "\fIA class for \fIfinite\fP \fIdifference\fP \fIapproximation\fP of \fBPeridynamics\fP\&. \fP"
.ti -1c
.RI "class \fBModel\fP"
.br
.RI "\fIA base class for different models\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of Peridynamic models\&. 

This namespace provides collection of Peridynamic models\&. Depending on the spatial discretization, e\&.g\&. finite difference, weak finite element, nodal finite element, and truss finite element, we get different implementation of model\&.
.PP
E\&.g\&., in \fBFDModel\fP we implement finite difference discretization with explicit time integration of Peridynamic equation\&.
.PP
\fBSee also:\fP
.RS 4
\fBFDModel\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
