.TH "rw" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rw \- Collection of methods and database related to reading and writing\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBreader\fP"
.br
.RI "\fICollection of methods and database related to reading\&. \fP"
.ti -1c
.RI " \fBwriter\fP"
.br
.RI "\fICollection of methods and database related to writing\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of methods and database related to reading and writing\&. 

This namespace provides methods and data members specific to reading and writing of the mesh data and simulation data\&.
.PP
\fBSee also:\fP
.RS 4
VtkReader, MshReader 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
