.TH "rw::reader" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rw::reader \- Collection of methods and database related to reading\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMshReader\fP"
.br
.RI "\fIA class to read Gmsh (msh) mesh files\&. \fP"
.ti -1c
.RI "class \fBVtkReader\fP"
.br
.RI "\fIA class to read vtk (vtu) mesh files\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreadCsvFile\fP (const std::string &filename, size_t dim, std::vector< \fButil::Point3\fP > *nodes, std::vector< double > *volumes)"
.br
.RI "\fIReads mesh data into node file and element file\&. \fP"
.ti -1c
.RI "void \fBreadVtuFile\fP (const std::string &filename, size_t dim, std::vector< \fButil::Point3\fP > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)"
.br
.RI "\fIReads mesh data into node file and element file\&. \fP"
.ti -1c
.RI "void \fBreadMshFile\fP (const std::string &filename, size_t dim, std::vector< \fButil::Point3\fP > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)"
.br
.RI "\fIReads mesh data into node file and element file\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of methods and database related to reading\&. 

This namespace provides methods and data members specific to reading of the mesh data\&. Currently, \&.csv, \&.vtu and \&.msh files are supported\&.
.PP
\fBSee also:\fP
.RS 4
\fBVtkReader\fP, \fBMshReader\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void rw::reader::readCsvFile (const std::string & filename, size_t dim, std::vector< \fButil::Point3\fP > * nodes, std::vector< double > * volumes)"

.PP
Reads mesh data into node file and element file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP name of mesh file 
.br
\fIdim\fP dimension 
.br
\fInodes\fP vector of nodes data 
.br
\fIvolumes\fP vector holding volume of the nodes 
.RE
.PP

.PP
Referenced by fe::Mesh::createData()\&.
.SS "void rw::reader::readMshFile (const std::string & filename, size_t dim, std::vector< \fButil::Point3\fP > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = \fCfalse\fP)"

.PP
Reads mesh data into node file and element file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP name of mesh file 
.br
\fIdim\fP dimension 
.br
\fInodes\fP vector of nodes data 
.br
\fIelement_type\fP type of element 
.br
\fInum_elem\fP number of elements 
.br
\fIenc\fP vector holding element-node connectivity 
.br
\fInec\fP vector holding node-element connectivity 
.br
\fIvolumes\fP vector holding volume of the nodes 
.br
\fIis_fd\fP flag indicating if this mesh is for finite_difference simulation 
.RE
.PP

.PP
Referenced by fe::Mesh::createData()\&.
.SS "void rw::reader::readVtuFile (const std::string & filename, size_t dim, std::vector< \fButil::Point3\fP > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = \fCfalse\fP)"

.PP
Reads mesh data into node file and element file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP name of mesh file 
.br
\fIdim\fP dimension 
.br
\fInodes\fP vector of nodes data 
.br
\fIelement_type\fP type of element 
.br
\fInum_elem\fP number of elements 
.br
\fIenc\fP vector holding element-node connectivity 
.br
\fInec\fP vector holding node-element connectivity 
.br
\fIvolumes\fP vector holding volume of the nodes 
.br
\fIis_fd\fP flag indicating if this mesh is for finite_difference simulation 
.RE
.PP

.PP
Referenced by fe::Mesh::createData()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
