.TH "rw::reader::MshReader" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rw::reader::MshReader \- A class to read Gmsh (msh) mesh files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mshReader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMshReader\fP (const std::string &filename)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "void \fBreadMesh\fP (size_t dim, std::vector< \fButil::Point3\fP > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)"
.br
.RI "\fIReads mesh data into node file and element file\&. \fP"
.in -1c
.SS "Private Attributes"

.PP
.RI "\fBInternal data\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "const std::string \fBd_filename\fP"
.br
.RI "\fIfilename \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
A class to read Gmsh (msh) mesh files\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rw::reader::MshReader::MshReader (const std::string & filename)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP name of mesh file 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void rw::reader::MshReader::readMesh (size_t dim, std::vector< \fButil::Point3\fP > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = \fCfalse\fP)"

.PP
Reads mesh data into node file and element file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdim\fP Dimension 
.br
\fInodes\fP vector of nodes data 
.br
\fIelement_type\fP type of element 
.br
\fInum_elem\fP number of elements 
.br
\fIenc\fP vector holding element-node connectivity 
.br
\fInec\fP vector holding node-element connectivity 
.br
\fIvolumes\fP vector holding volume of the nodes 
.br
\fIis_fd\fP flag indicating if this mesh is for finite_difference simulation 
.RE
.PP

.PP
Referenced by rw::reader::readMshFile()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
