rw::reader
NAME
rw::reader - Collection of methods and database related to reading.
SYNOPSIS
Data Structures
class MshReader
A class to read Gmsh (msh) mesh files.
class VtkReader
A class to read vtk (vtu) mesh files.
Functions
void readCsvFile (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, std::vector< double > *volumes)
Reads mesh data into node file and element file.
void readVtuFile (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)
Reads mesh data into node file and element file.
void readMshFile (const std::string &filename, size_t dim, std::vector< util::Point3 > *nodes, size_t &element_type, size_t &num_elem, std::vector< size_t > *enc, std::vector< std::vector< size_t >> *nec, std::vector< double > *volumes, bool is_fd=false)
Reads mesh data into node file and element file.
Detailed Description
Collection of methods and database related to reading.
This namespace provides methods and data members specific to reading of the mesh data. Currently, .csv, .vtu and .msh files are supported.
See also:
VtkReader, MshReader
Function Documentation
void rw::reader::readCsvFile (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, std::vector< double > * volumes)
Reads mesh data into node file and element file.
Parameters:
filename name of mesh file
dim dimension
nodes vector of nodes data
volumes vector holding volume of the nodes
Referenced by fe::Mesh::createData().
void rw::reader::readMshFile (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = false)
Reads mesh data into node file and element file.
Parameters:
filename name of mesh file
dim dimension
nodes vector of nodes data
element_type type of element
num_elem number of elements
enc vector holding element-node connectivity
nec vector holding node-element connectivity
volumes vector holding volume of the nodes
is_fd flag indicating if this mesh is for finite_difference simulation
Referenced by fe::Mesh::createData().
void rw::reader::readVtuFile (const std::string & filename, size_t dim, std::vector< util::Point3 > * nodes, size_t & element_type, size_t & num_elem, std::vector< size_t > * enc, std::vector< std::vector< size_t >> * nec, std::vector< double > * volumes, bool is_fd = false)
Reads mesh data into node file and element file.
Parameters:
filename name of mesh file
dim dimension
nodes vector of nodes data
element_type type of element
num_elem number of elements
enc vector holding element-node connectivity
nec vector holding node-element connectivity
volumes vector holding volume of the nodes
is_fd flag indicating if this mesh is for finite_difference simulation
Referenced by fe::Mesh::createData().
Author
Generated automatically by Doxygen for NLMech from the source code.