.TH "util" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util \- Collection of methods useful in simulation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcompare\fP"
.br
.RI "\fIProvides comparison of floating point values\&. \fP"
.ti -1c
.RI " \fBtransformation\fP"
.br
.RI "\fIProvides geometrical methods such rotation of a vector\&. \fP"
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMatrix3\fP"
.br
.RI "\fIA structure to represent 3d matrices\&. \fP"
.ti -1c
.RI "struct \fBPoint3\fP"
.br
.RI "\fIA structure to represent 3d vectors\&. \fP"
.ti -1c
.RI "struct \fBSymMatrix3\fP"
.br
.RI "\fIA structure to represent 3d symmetric matrices\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef blaze::DynamicVector< double, blaze::columnVector > \fBVectorXi\fP"
.br
.RI "\fIBlaze: Definition of vector\&. \fP"
.ti -1c
.RI "typedef blaze::DynamicMatrix< double > \fBMatrixij\fP"
.br
.RI "\fIBlaze: Definition of n x m matrix\&. \fP"
.ti -1c
.RI "typedef blaze::SymmetricMatrix< blaze::DynamicMatrix< double > > \fBSymMatrixij\fP"
.br
.RI "\fIBlaze: Definition of n x n symmetric matrix\&. \fP"
.ti -1c
.RI "typedef blaze::StaticMatrix< double, 3UL, 3UL > \fBMatrix33\fP"
.br
.RI "\fIBlaze: Definition of 3 x 3 matrix\&. \fP"
.ti -1c
.RI "typedef blaze::SymmetricMatrix< blaze::StaticMatrix< double, 3UL, 3UL > > \fBSymMatrix33\fP"
.br
.RI "\fIBlaze: Definition of 3 x 3 symmetric matrix\&. \fP"
.ti -1c
.RI "typedef blaze::StaticVector< double, 3UL > \fBVector3\fP"
.br
.RI "\fIBlaze: Definition of 3D vector\&. \fP"
.ti -1c
.RI "typedef blaze::IdentityMatrix< double > \fBIdentityMatrix\fP"
.br
.RI "\fIBlaze: Identity matrix\&. \fP"
.ti -1c
.RI "typedef blaze::DynamicVector< float, blaze::columnVector > \fBVectorFXi\fP"
.br
.RI "\fIBlaze: Definition of vector\&. \fP"
.ti -1c
.RI "typedef blaze::DynamicMatrix< float > \fBMatrixFij\fP"
.br
.RI "\fIBlaze: Definition of n x m matrix\&. \fP"
.ti -1c
.RI "typedef blaze::SymmetricMatrix< blaze::DynamicMatrix< float > > \fBSymMatrixFij\fP"
.br
.RI "\fIBlaze: Definition of n x n symmetric matrix\&. \fP"
.ti -1c
.RI "typedef blaze::StaticMatrix< float, 3UL, 3UL > \fBMatrixF33\fP"
.br
.RI "\fIBlaze: Definition of 3 x 3 matrix\&. \fP"
.ti -1c
.RI "typedef blaze::SymmetricMatrix< blaze::StaticMatrix< float, 3UL, 3UL > > \fBSymMatrixF33\fP"
.br
.RI "\fIBlaze: Definition of 3 x 3 symmetric matrix\&. \fP"
.ti -1c
.RI "typedef blaze::StaticVector< float, 3UL > \fBVectorF3\fP"
.br
.RI "\fIBlaze: Definition of 3D vector\&. \fP"
.ti -1c
.RI "typedef blaze::IdentityMatrix< float > \fBIdentityMatrixF\fP"
.br
.RI "\fIBlaze: Identity matrix\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBaddInplace\fP (std::vector< \fButil::Point3\fP > &a, std::vector< \fButil::Point3\fP > b)"
.br
.RI "\fIAdds point b to point a inplace\&. \fP"
.ti -1c
.RI "static void \fBsubInplace\fP (std::vector< \fButil::Point3\fP > &a, std::vector< \fButil::Point3\fP > b)"
.br
.RI "\fISubtracts point b to point a inplace\&. \fP"
.ti -1c
.RI "void \fBcopy\fP (std::vector< \fButil::Point3\fP > a, std::vector< \fButil::Point3\fP > &b)"
.br
.RI "\fICopys vector's a content to b\&. \fP"
.ti -1c
.RI "std::vector< \fButil::Point3\fP > \fBadd\fP (std::vector< \fButil::Point3\fP > a, std::vector< \fButil::Point3\fP > b)"
.br
.RI "\fIAdds vector of points b to vector of points a in a element wise manner\&. \fP"
.ti -1c
.RI "std::vector< \fButil::Point3\fP > \fBsubb\fP (std::vector< \fButil::Point3\fP > a, std::vector< \fButil::Point3\fP > b)"
.br
.RI "\fISubtracts vector of points b to vector of points a in a element-wise manner\&. \fP"
.in -1c
.SS "Variables"

.PP
.RI "\fBVTK Element types\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static const int \fBvtk_type_vertex\fP = 1"
.br
.RI "\fIElement type (for vtk) \fP"
.ti -1c
.RI "static const int \fBvtk_type_poly_vertex\fP = 2"
.br
.ti -1c
.RI "static const int \fBvtk_type_line\fP = 3"
.br
.ti -1c
.RI "static const int \fBvtk_type_poly_line\fP = 4"
.br
.ti -1c
.RI "static const int \fBvtk_type_triangle\fP = 5"
.br
.ti -1c
.RI "static const int \fBvtk_type_triangle_strip\fP = 6"
.br
.ti -1c
.RI "static const int \fBvtk_type_polygon\fP = 7"
.br
.ti -1c
.RI "static const int \fBvtk_type_pixel\fP = 8"
.br
.ti -1c
.RI "static const int \fBvtk_type_quad\fP = 9"
.br
.ti -1c
.RI "static const int \fBvtk_type_tetra\fP = 10"
.br
.ti -1c
.RI "static const int \fBvtk_type_voxel\fP = 11"
.br
.ti -1c
.RI "static const int \fBvtk_type_hexahedron\fP = 12"
.br
.ti -1c
.RI "static const int \fBvtk_type_wedge\fP = 13"
.br
.ti -1c
.RI "static const int \fBvtk_type_pyramid\fP = 14"
.br
.ti -1c
.RI "static int \fBvtk_map_element_to_num_nodes\fP [16]"
.br
.RI "\fIMap from element type to number of nodes (for vtk) \fP"
.in -1c
.in -1c
.PP
.RI "\fBGmsh Element types\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static const int \fBmsh_type_line\fP = 1"
.br
.RI "\fIElement type (for gmsh) \fP"
.ti -1c
.RI "static const int \fBmsh_type_triangle\fP = 2"
.br
.ti -1c
.RI "static const int \fBmsh_type_quadrangle\fP = 3"
.br
.ti -1c
.RI "static const int \fBmsh_type_tetrahedron\fP = 4"
.br
.ti -1c
.RI "static const int \fBmsh_type_hexahedron\fP = 5"
.br
.ti -1c
.RI "static const int \fBmsh_type_prism\fP = 6"
.br
.ti -1c
.RI "static const int \fBmsh_type_pyramid\fP = 7"
.br
.ti -1c
.RI "static const int \fBmsh_type_line_second_order\fP = 8"
.br
.ti -1c
.RI "static const int \fBmsh_type_traingle_second_order\fP = 9"
.br
.ti -1c
.RI "static const int \fBmsh_type_quadrangle_second_order\fP = 10"
.br
.ti -1c
.RI "static const int \fBmsh_type_vertex\fP = 15"
.br
.ti -1c
.RI "static int \fBmsh_map_element_to_num_nodes\fP [16]"
.br
.RI "\fIMap from element type to number of nodes (for msh) \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Collection of methods useful in simulation\&. 

This namespace provides number of useful functions and struct definition\&.
.PP
\fBSee also:\fP
.RS 4
\fBPoint3\fP, \fBMatrix3\fP, \fBSymMatrix3\fP, \fBcompare\fP, \fBtransformation\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "std::vector<\fButil::Point3\fP> util::add (std::vector< \fButil::Point3\fP > a, std::vector< \fButil::Point3\fP > b)\fC [inline]\fP"

.PP
Adds vector of points b to vector of points a in a element wise manner\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP vector of points 
.br
\fIb\fP vector of points 
.RE
.PP
\fBReturns:\fP
.RS 4
Vector vector of point after element wise addition 
.RE
.PP

.SS "static void util::addInplace (std::vector< \fButil::Point3\fP > & a, std::vector< \fButil::Point3\fP > b)\fC [inline]\fP, \fC [static]\fP"

.PP
Adds point b to point a inplace\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Point a 
.br
\fIb\fP Point b 
.RE
.PP

.SS "void util::copy (std::vector< \fButil::Point3\fP > a, std::vector< \fButil::Point3\fP > & b)\fC [inline]\fP"

.PP
Copys vector's a content to b\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP vector of points 
.br
\fIb\fP vector of points 
.RE
.PP

.SS "std::vector<\fButil::Point3\fP> util::subb (std::vector< \fButil::Point3\fP > a, std::vector< \fButil::Point3\fP > b)\fC [inline]\fP"

.PP
Subtracts vector of points b to vector of points a in a element-wise manner\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Point a 
.br
\fIb\fP Point b 
.RE
.PP
\fBReturns:\fP
.RS 4
Vector vector of points after element-wise subtraction 
.RE
.PP

.SS "static void util::subInplace (std::vector< \fButil::Point3\fP > & a, std::vector< \fButil::Point3\fP > b)\fC [inline]\fP, \fC [static]\fP"

.PP
Subtracts point b to point a inplace\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Point a 
.br
\fIb\fP Point b 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
