.TH "util::Matrix3" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::Matrix3 \- A structure to represent 3d matrices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrix\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix3\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "float \fBd_xx\fP"
.br
.RI "\fIthe xx component \fP"
.ti -1c
.RI "float \fBd_xy\fP"
.br
.RI "\fIthe xy component \fP"
.ti -1c
.RI "float \fBd_xz\fP"
.br
.RI "\fIthe xz component \fP"
.ti -1c
.RI "float \fBd_yx\fP"
.br
.RI "\fIthe yx component \fP"
.ti -1c
.RI "float \fBd_yy\fP"
.br
.ti -1c
.RI "float \fBd_yz\fP"
.br
.RI "\fIthe yz component \fP"
.ti -1c
.RI "float \fBd_zx\fP"
.br
.RI "\fIthe zx component \fP"
.ti -1c
.RI "float \fBd_zy\fP"
.br
.RI "\fIthe zy component \fP"
.ti -1c
.RI "float \fBd_zz\fP"
.br
.RI "\fIthe zz component \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
A structure to represent 3d matrices\&. 
.SH "Field Documentation"
.PP 
.SS "float util::Matrix3::d_yx"

.PP
the yx component the yy component 

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
