.TH "util::Point3" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::Point3 \- A structure to represent 3d vectors\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint3\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "\fBPoint3\fP (double x, double y, double z)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "double \fBlength\fP ()"
.br
.RI "\fIComputes the Euclidean length of the vector\&. \fP"
.ti -1c
.RI "double \fBdot\fP (\fBPoint3\fP b)"
.br
.RI "\fIComputes the dot product of this vector with another point\&. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBd_x\fP"
.br
.RI "\fIthe x coordinate \fP"
.ti -1c
.RI "double \fBd_y\fP"
.br
.RI "\fIthe y coordinate \fP"
.ti -1c
.RI "double \fBd_z\fP"
.br
.RI "\fIthe z coordinate \fP"
.in -1c
.SS "Group operators"

.in +1c
.ti -1c
.RI "\fBPoint3\fP & \fBoperator+=\fP (const double b)"
.br
.ti -1c
.RI "\fBPoint3\fP & \fBoperator\-=\fP (const double b)"
.br
.ti -1c
.RI "\fBPoint3\fP & \fBoperator*=\fP (const double b)"
.br
.ti -1c
.RI "\fBPoint3\fP & \fBoperator+=\fP (const \fBPoint3\fP &b)"
.br
.ti -1c
.RI "\fBPoint3\fP & \fBoperator\-=\fP (const \fBPoint3\fP &b)"
.br
.ti -1c
.RI "\fBPoint3\fP & \fBoperator*=\fP (const \fBPoint3\fP &b)"
.br
.ti -1c
.RI "\fBPoint3\fP & \fBoperator/=\fP (const double b)"
.br
.ti -1c
.RI "double & \fBoperator[]\fP (size_t i)"
.br
.ti -1c
.RI "\fBPoint3\fP \fBoperator+\fP (\fBPoint3\fP lhs, const \fBPoint3\fP &rhs)"
.br
.ti -1c
.RI "\fBPoint3\fP \fBoperator\-\fP (\fBPoint3\fP lhs, const \fBPoint3\fP &rhs)"
.br
.ti -1c
.RI "\fBPoint3\fP \fBoperator*\fP (\fBPoint3\fP lhs, const double rhs)"
.br
.ti -1c
.RI "\fBPoint3\fP \fBoperator/\fP (\fBPoint3\fP lhs, const double rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A structure to represent 3d vectors\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "util::Point3::Point3 (double x, double y, double z)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The x coordinate 
.br
\fIy\fP The y coordinate 
.br
\fIz\fP The z coordinate 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double util::Point3::dot (\fBPoint3\fP b)\fC [inline]\fP"

.PP
Computes the dot product of this vector with another point\&. 
.PP
\fBParameters:\fP
.RS 4
\fIb\fP Another vector 
.RE
.PP
\fBReturns:\fP
.RS 4
Value a dot product 
.RE
.PP

.SS "double util::Point3::length ()\fC [inline]\fP"

.PP
Computes the Euclidean length of the vector\&. 
.PP
\fBReturns:\fP
.RS 4
Length Euclidean length of the vector 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
