.TH "util::SymMatrix3" 3 "Thu Apr 4 2019" "NLMech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util::SymMatrix3 \- A structure to represent 3d symmetric matrices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrix\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSymMatrix3\fP ()"
.br
.RI "\fIConstructor\&. \fP"
.in -1c
.SS "Data Fields"

.PP
.RI "\fBData members\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "float \fBd_xx\fP"
.br
.RI "\fIthe xx component \fP"
.ti -1c
.RI "float \fBd_yy\fP"
.br
.RI "\fIthe yy component \fP"
.ti -1c
.RI "float \fBd_zz\fP"
.br
.RI "\fIthe zz component \fP"
.ti -1c
.RI "float \fBd_xy\fP"
.br
.RI "\fIthe xy (yx) component \fP"
.ti -1c
.RI "float \fBd_xz\fP"
.br
.RI "\fIthe xz (zx) component \fP"
.ti -1c
.RI "float \fBd_yz\fP"
.br
.RI "\fIthe yz (zy) component \fP"
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
A structure to represent 3d symmetric matrices\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for NLMech from the source code\&.
